### ISSUE TITLE
Support for Unix sockets

### ISSUE THREAD

**Issue by carnager** [bentglasstube/Net-MPD#8]
MPD allows to set a unix socket instead of a TCP socket. Most clients work with these just fine, but Net::MPD will try to connect to `/path/to/socket:6600` which will obviously fail.

It would be great if support for Unix sockets could be added!

**Comment by spul** [comment]
+1

**Comment by bentglasstube** [comment]
Added support in e757037bf50f96bb303ab1f33ad854aae8e5b677, which is included in release 0.07.  This is being published to CPAN now.  Enjoy.
